const assert=require('node:assert/strict');
const test=require('node:test');
const fs=require('node:fs');
const path=require('node:path');
const X=require('../vendor/xlsx.full.min.js');
X.set_fs(fs);
const C=require('../core.js');
function table(rows,merges=[]){const s=X.utils.aoa_to_sheet(rows);s['!merges']=merges;return C.fromSheet(s,X);}
function cfg(t,overrides={}){return {hs:1,he:1,ds:2,de:t.rows.length,key:0,aux:-1,...overrides};}
const a=table([['姓名','工号','部门'],['王芳','001','工程'],['张伟','002','工程'],['张伟','003','设备'],['张伟','004','综合'],['刘洋','005','工程'],['刘洋','006','设备'],['陈晨','007','综合']]);
const b=table([['人员姓名','员工编号','电话'],['李明','008','13900000000'],['张伟','002','13800000001'],['张伟','003','13800000002'],['刘洋','005','13800000003'],['刘洋','006','13800000004'],['陈晨','007','13800000005']]);
test('name frequency diff, duplicates and source row numbers',()=>{const r=C.compare(a,b,cfg(a),cfg(b));assert.equal(r.items.filter(x=>x.different).length,3);assert.equal(r.items.filter(x=>x.duplicate).length,2);assert.equal(r.items.find(x=>x.name==='张伟').status,'A 多 1 条');assert.deepEqual(r.items.find(x=>x.name==='张伟').a.map(x=>x.row),[3,4,5]);assert.equal(r.items.find(x=>x.name==='刘洋').different,false);});
test('supplement preserves rows/order and never silently selects duplicate names',()=>{const r=C.supplement(a,b,cfg(a),cfg(b),[2]);assert.equal(r.items.length,7);assert.deepEqual(r.items.map(x=>x.master.row),[2,3,4,5,6,7,8]);assert.equal(r.items.filter(x=>x.status==='重名待确认').length,5);assert.equal(r.items[0].status,'未匹配');assert.equal(r.items.at(-1).values[0],'13800000005');assert.equal(r.items[1].values[0],'');});
test('auxiliary key distinguishes individuals and uses source values',()=>{const r=C.supplement(a,b,cfg(a,{aux:1}),cfg(b,{aux:1}),[2]);assert.equal(r.items.filter(x=>x.chosen).length,5);assert.equal(r.items[1].values[0],'13800000001');assert.equal(r.items[3].chosen,null);});
test('manual choice is restricted to matching candidates and is auditable',()=>{let r=C.supplement(a,b,cfg(a),cfg(b),[2],{}, {3:4});assert.equal(r.items[1].values[0],'13800000002');assert.equal(r.items[1].manual,true);r=C.supplement(a,b,cfg(a),cfg(b),[2],{}, {3:2});assert.equal(r.items[1].chosen,null);});
test('blank and missing auxiliary keys not matched; blank rows skipped',()=>{const t=table([['姓名','工号'],['A',''],['','003'],['',''],['A','001']]);const r=C.compare(t,t,cfg(t,{aux:1}),cfg(t,{aux:1}));assert.equal(r.invalid.length,4);assert.equal(r.items.length,1);assert.deepEqual(r.skipped,[1,1]);});
test('zero, leading zeros, O/0 and internal spaces remain distinct by default',()=>{const t=table([['编号'],['0012'],['12'],['O01'],['001'],['张 三'],['张三'],['0'],[' 张三 ']]);const r=C.compare(t,t,cfg(t),cfg(t));assert.equal(r.items.length,7);assert.equal(r.items.find(x=>x.name==='张三').a.length,2);assert.equal(C.compare(t,t,cfg(t),cfg(t),{spaces:true}).items.length,6);});
test('header range late in sheet and merged hierarchy',()=>{const t=table([['报表'],[],[],[],[],['姓名','联系方式',''],['','手机','电话'],['陈晨','13800000000','01012345678']],[{s:{r:5,c:0},e:{r:6,c:0}},{s:{r:5,c:1},e:{r:5,c:2}}]);const c=C.detect(t);assert.equal(c.hs,6);assert.equal(c.he,7);assert.equal(c.ds,8);assert.deepEqual(C.labels(t,c),['姓名','联系方式 / 手机','联系方式 / 电话']);});
test('data merges block counting and supplementation; header merges do not',()=>{const t=table([['姓名','手机'],['张伟','123'],['','456']],[{s:{r:1,c:0},e:{r:2,c:0}}]);assert.throws(()=>C.compare(t,b,cfg(t),cfg(b)),/合并单元格/);const s=table([['姓名','手机'],['张伟','123'],['李明','']],[{s:{r:1,c:1},e:{r:2,c:1}}]);assert.throws(()=>C.supplement(a,s,cfg(a),cfg(s),[1]),/合并单元格/);});
test('same-name fields are appended with unique labels without overwriting',()=>{const r=C.supplement(a,b,cfg(a),cfg(b),[0]);assert.equal(r.headers.length,4);assert.equal(r.items.at(-1).master.values[2],'综合');const t=table([['姓名','部门'],['陈晨','工程']]);const r2=C.supplement(a,t,cfg(a),cfg(t),[1]);assert.equal(r2.added[0],'部门（来自资料表）');});
test('missing selected field is explicitly flagged',()=>{const t=table([['姓名','电话'],['陈晨','']]);const r=C.supplement(a,t,cfg(a),cfg(t),[1]);assert.equal(r.items.at(-1).status,'来源资料缺失');});
test('invalid ranges and unpaired auxiliary columns rejected',()=>{assert.throws(()=>C.compare(a,b,cfg(a,{ds:1}),cfg(b)),/表头/);assert.throws(()=>C.compare(a,b,cfg(a,{aux:1}),cfg(b)),/辅助列/);assert.throws(()=>C.compare(a,b,cfg(a,{ds:2.5}),cfg(b)),/整数/);});
test('real XLS / XLSX round trip preserves merged headers and text identifiers',()=>{const dir=path.join(__dirname,'fixtures');fs.mkdirSync(dir,{recursive:true});for(const type of ['xls','xlsx']){const rows=[['人员登记'],['演示数据'],[],[],[],['姓名','基本资料','','联系方式'],['','工号','部门','手机'],['王芳','0001','工程部',''],['张伟','0002','设备部',''],['张伟','0003','综合部',''],['陈晨','0004','工程部','']];const s=X.utils.aoa_to_sheet(rows);s['!merges']=[{s:{r:0,c:0},e:{r:0,c:3}},{s:{r:5,c:0},e:{r:6,c:0}},{s:{r:5,c:1},e:{r:5,c:2}}];const wb=X.utils.book_new();X.utils.book_append_sheet(wb,s,'多行表头');const filename=path.join(dir,'master.'+type);X.writeFile(wb,filename,{bookType:type==='xls'?'biff8':'xlsx'});const back=X.readFile(filename,{cellText:true,raw:true});const parsed=C.fromSheet(back.Sheets['多行表头'],X);assert.equal(parsed.rows[7][1],'0001');assert.equal(parsed.merges.length,3);assert.equal(C.detect(parsed).hs,6);assert.equal(C.detect(parsed).he,7);assert.deepEqual(C.labels(parsed,C.detect(parsed)),['姓名','基本资料 / 工号','基本资料 / 部门','联系方式 / 手机']);}
 const wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([['人员姓名','员工编号','手机','部门'],['陈晨','0004','13800000004','工程部'],['张伟','0003','13800000003','综合部'],['李明','0005','13800000005','设备部'],['张伟','0002','13800000002','设备部']]),'资料');X.writeFile(wb,path.join(dir,'source.xlsx'));
});
test('HTML disguised as XLS is readable',()=>{const html='<html><meta charset="utf-8"><table><tr><td>姓名</td><td>工号</td></tr><tr><td>陈晨</td><td>0004</td></tr></table></html>';const wb=X.read(html,{type:'string',raw:true});const t=C.fromSheet(wb.Sheets[wb.SheetNames[0]],X);assert.equal(t.rows[1][0],'陈晨');assert.equal(t.rows[1][1],'0004');fs.writeFileSync(path.join(__dirname,'fixtures','html-table.xls'),html);});
test('500 rows, permuted source, sums of occurrences and supplementary data',()=>{const rows=[['姓名','手机'],...Array.from({length:500},(_,i)=>['人员'+i,'138'+String(i).padStart(8,'0')])];const x=table(rows),y=table([rows[0],...rows.slice(1).reverse()]);assert.equal(C.compare(x,y,cfg(x),cfg(y)).items.filter(x=>x.different).length,0);const r=C.supplement(x,y,cfg(x),cfg(y),[1]);assert.equal(r.items.filter(x=>x.chosen).length,500);assert.equal(r.items[320].values[0],rows[321][1]);});
